### ISSUE TITLE
Github cloned projects could'nt be run.

### ISSUE THREAD

**Issue by JosephVoid** [londonappbrewery/dicee-flutter#11]
Whenever i try to run cloned projects from Github....It says "Running gradle task 'assembleDebug'.." and stays like that forever.But when i create new flutter projects and copy your code it works...any ideas on what could be the problem.

**Comment by emad-sure** [comment]
@JosephVoid actually this happened with me too ,
first time i opened pubspec.yaml and make pub get but it hangs on Running gradle task 
you should run **Pub upgrade** then build again

**Comment by mihir2286** [comment]
Giving below error on Run every project .

Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Kishlay222** [comment]
continuously showing this error.... 
  Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Running Gradle task 'assembleDebug'...
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:169)
	at org.gradle.wrapper.Install.unzip(Install.java:214)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:74)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:65)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
[!] Gradle threw an error while trying to update itself. Retrying the update...
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by deepdhar** [comment]
I'm having the same issue. The cloned projects from GIT didn't run at all, infact it doesn't detect dependencies too when I click on get dependencies. Why am I facing this, kindly help?

**Comment by deepakDOTexe** [comment]
I am a newbie to android studio so I don't know exactly what the problem was, but in my  _android/gradle/build.gradle_ file of the cloned project I edited the following line 

> classpath 'com.android.tools.build:gradle:3.5.3'

to

> classpath 'com.android.tools.build:gradle:3.5.0'


which was similar to the projects created by me offline. This might be due to running an older version of this gradle stuff on my machine. I am not sure but it worked for me for the time being.

**Comment by rohanchauhan** [comment]
You can try running with flutter run command with a verbose flag. 
1. It's because Gradle cannot be downloaded because you haven't added Android Studio to Windows Firewall exceptions.
2. It's the migration problem for which you can make similar changes as I have suggested here: https://github.com/londonappbrewery/mi_card_flutter/issues/28

After doing these two things, I am able to run all of the projects. Hope this helps!

**Comment by shyam-999** [comment]
when will this 'assembleDebug'... gonna end ???

**Comment by Delocalized-electron** [comment]
> 
> 
> when will this 'assembleDebug'... gonna end ???

Add flutter to the PATH and then retry

**Comment by rmahmadkhan** [comment]
I'm getting this exception only on this project.
`Exception: Gradle task assembleDebug failed with exit code 1`

I have run multiple other projects and those are working fine. I even tried all the things told above.

**Comment by aviralguptaa** [comment]
Go to file>Project Structure>and see project SDK most of the time it is not set set it.
Copy the SDF from SDK manager from top right of your android studio window.
